Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "jenkins"


  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 80, host: 8081
  config.vm.network "private_network", ip: "192.168.56.91"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.gui = false
  end

  # Jenkins requires 10GB+ of drive space. The default Vagrant disk size might
  # not be enough. If you need to resize the disk, you can use the
  # vagrant-disksize plugin.
  # 1. Install the plugin: vagrant plugin install vagrant-disksize
  # 2. Uncomment the following line:
  # config.disksize.size = '10GB'

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y openjdk-21-jdk
    sudo mkdir -p /usr/share/keyrings
    sudo wget -O /usr/share/keyrings/jenkins-keyring.asc \
      https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]" \
      https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
      /etc/apt/sources.list.d/jenkins.list > /dev/null
    sudo apt-get update
    sudo apt-get install -y jenkins
    sudo apt-get install -y nginx
    echo
    echo "###################"
    echo  "installation completed"
    echo "###################"
  SHELL
end
